/**
 * /compact — ask the model to summarize the conversation, keep the summary.
 *
 * The engine owns compaction of its own history (SlidingWindowStrategy evicts
 * turns near the window), but it has no "compact now" entry point, and its
 * eviction is lossy by construction: it drops turns, it does not digest them.
 * `/compact` is the deliberate version — a model-generated summary that the
 * next session is seeded with, so the thread survives losing its bulk.
 *
 * Two rules this module exists to keep:
 *   1. The summary is generated by the model. A hand-rolled string that says
 *      "42 messages summarized" while listing the last eight prompts is not a
 *      summary, it is a claim, and the model that reads it next knows nothing
 *      it did not already know.
 *   2. Nothing is destroyed until a summary exists. Compaction that fails must
 *      leave the conversation exactly as it was.
 */
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { generateText } from "ai-sdk-cpp";
import { createModel } from "./provider/registry.js";
import { getDataDir } from "../state/storage.js";
import { writeToFile } from "../utils/exportConversation.js";
import type { Message, ProviderConfig, TokenUsage } from "../types/index.js";

/**
 * The transcript handed to the summarizer, capped. A conversation big enough
 * to need compacting is by definition too big to send whole at full fidelity,
 * so what is elided is the middle: the opening states the goal, the tail holds
 * the current state, and the middle is the part whose details have already
 * been superseded.
 */
export const MAX_TRANSCRIPT_CHARS = 400_000;

/** Below this a "summary" is a shrug; the attempt counts as failed. */
export const MIN_SUMMARY_CHARS = 40;

/** Ceiling on the summary itself. Long enough for real detail, short enough
 *  that the next session is genuinely lighter than the one it replaced. */
export const MAX_SUMMARY_TOKENS = 4096;

/** The reference gives up after three; so do we, and then we change nothing. */
export const MAX_COMPACTION_ATTEMPTS = 3;

export const COMPACTION_SYSTEM_PROMPT = [
  "You summarize an in-progress coding session so that another assistant can",
  "continue the work with no access to the original conversation.",
  "",
  "Write the summary as prose under these headings, omitting any that are empty:",
  "",
  "## Goal",
  "What the user asked for, in their terms. Include constraints they stated.",
  "",
  "## Decisions",
  "Approaches chosen and rejected, with the reason. A decision without its",
  "reason gets re-litigated by the next assistant.",
  "",
  "## Files",
  "Every file created, modified or read for a reason, with what changed in it.",
  "Exact paths.",
  "",
  "## State",
  "What is done and verified, what is in progress, what is known broken.",
  "Include exact commands that were run and their results when they matter.",
  "",
  "## Next",
  "The immediate next steps, in order.",
  "",
  "Keep every fact that would be expensive to rediscover: error messages, API",
  "shapes, numbers, names. Drop pleasantries and repetition. Never invent",
  "anything that is not in the conversation.",
].join("\n");

/** One line the model can see, so a compacted session explains itself. */
export function compactionNotice(opts: {
  summarized: number;
  archivedTo?: string;
}): string {
  const archived = opts.archivedTo ? ` The full transcript is archived at ${opts.archivedTo} — read it if you need a detail this summary omits.` : "";
  return `[Context compacted: the ${opts.summarized} messages above were summarized below.${archived}]`;
}

function oneLine(text: string, max: number): string {
  const flat = text.replace(/\s+/g, " ").trim();
  return flat.length > max ? flat.slice(0, max) + " …" : flat;
}

/** What each message looked like, for the summarizer's eyes only. */
export function renderMessage(msg: Message): string {
  const parts: string[] = [];
  const body = msg.content?.trim();
  if (body) parts.push(body);
  for (const tool of msg.toolUse ?? []) {
    const args = tool.input ? oneLine(tool.input, 400) : "";
    parts.push(`[tool ${tool.toolName}${args ? ` ${args}` : ""}]`);
    if (tool.output) parts.push(`[result] ${tool.output}`);
    // A failed call is a fact worth keeping — it is the thing the next
    // assistant would otherwise try again.
    if (tool.status === "error" || tool.status === "rejected" || tool.status === "interrupted") {
      parts.push(`[the tool call ${tool.status}]`);
    }
  }
  if (parts.length === 0) return "";
  return `${msg.role}: ${parts.join("\n")}`;
}

/**
 * Flatten the conversation into the text the summarizer reads. Tool calls and
 * their results are kept: in a coding session they carry most of the facts
 * worth preserving (what a file contained, what a command printed), and a
 * summary built from chat turns alone loses exactly those.
 */
export function renderTranscript(
  messages: readonly Message[],
  maxChars: number = MAX_TRANSCRIPT_CHARS,
): string {
  const rendered = messages
    .map(renderMessage)
    .filter((r) => r.trim().length > 0);

  if (rendered.length === 0) return "";

  const total = rendered.reduce((n, r) => n + r.length + 2, 0);
  if (total <= maxChars) return rendered.join("\n\n");

  // Keep the head (the goal) and the tail (the current state); elide the
  // middle. The head gets a third and the tail the rest, because recent state
  // is what the next turn actually needs.
  const headBudget = Math.floor(maxChars / 3);
  const tailBudget = maxChars - headBudget;

  const head: string[] = [];
  let used = 0;
  let headEnd = 0;
  for (; headEnd < rendered.length; headEnd++) {
    const next = rendered[headEnd]!.length + 2;
    if (used + next > headBudget) break;
    head.push(rendered[headEnd]!);
    used += next;
  }

  const tail: string[] = [];
  used = 0;
  let tailStart = rendered.length;
  for (; tailStart > headEnd; tailStart--) {
    const next = rendered[tailStart - 1]!.length + 2;
    if (used + next > tailBudget) break;
    tail.unshift(rendered[tailStart - 1]!);
    used += next;
  }

  const elided = rendered
    .slice(headEnd, tailStart)
    .reduce((n, r) => n + r.length, 0);
  const marker = `[… ${tailStart - headEnd} messages (${elided} characters) omitted: the conversation reached ${total} characters; the beginning and the most recent messages are kept in full …]`;

  return [...head, marker, ...tail].join("\n\n");
}

/**
 * Write the pre-compaction transcript somewhere it can be read again.
 *
 * Replacing the live message list is the point of compacting, but it must not
 * be the *only* copy: the debounced session save writes that list to disk, so
 * without this the compaction overwrites the saved transcript too, and neither
 * /resume nor /search could get it back. Markdown, because the next reader is
 * as likely to be the model as the user.
 */
export async function archiveTranscript(opts: {
  messages: readonly Message[];
  dir?: string;
  now?: number;
}): Promise<string> {
  const dir = opts.dir ?? join(getDataDir(), "compaction");
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const stamp = new Date(opts.now ?? Date.now()).toISOString().replace(/[:.]/g, "-");
  const path = join(dir, `${stamp}.md`);
  await writeToFile(opts.messages, "markdown", path, {
    includeSystem: true,
    includeThinking: true,
    maxToolOutputChars: 4000,
    title: "Pre-compaction transcript",
  });
  return path;
}

/** Accept a summary only if there is one. Whitespace and stubs are failures. */
export function normalizeSummary(text: string | undefined | null): string | null {
  const trimmed = (text ?? "").trim();
  return trimmed.length >= MIN_SUMMARY_CHARS ? trimmed : null;
}

export interface CompactionOptions {
  providerConfig: ProviderConfig;
  messages: readonly Message[];
  /** Abort the model call (the user pressed Esc). */
  signal?: AbortSignal;
}

export interface CompactionResult {
  summary: string;
  /** Messages handed to the summarizer. */
  summarized: number;
  transcriptChars: number;
  usage: TokenUsage;
  attempts: number;
}

/** Raised when every attempt failed. The caller must keep the transcript. */
export class CompactionFailed extends Error {
  constructor(message: string, readonly attempts: number) {
    super(message);
    this.name = "CompactionFailed";
  }
}

/**
 * Summarize `messages` with the model. Throws `CompactionFailed` — with the
 * transcript untouched — if no attempt produced usable text, so a failed
 * /compact is a no-op rather than a conversation-shaped hole.
 */
export async function summarizeConversation(
  opts: CompactionOptions,
): Promise<CompactionResult> {
  const transcript = renderTranscript(opts.messages);
  if (!transcript.trim()) {
    throw new CompactionFailed("There is nothing in this session to summarize.", 0);
  }

  const model = createModel(opts.providerConfig);
  let lastError = "";

  for (let attempt = 1; attempt <= MAX_COMPACTION_ATTEMPTS; attempt++) {
    if (opts.signal?.aborted) {
      throw new CompactionFailed("Compaction cancelled.", attempt - 1);
    }
    try {
      const result = await generateText({
        model,
        system: COMPACTION_SYSTEM_PROMPT,
        prompt: transcript,
        maxOutputTokens: MAX_SUMMARY_TOKENS,
      });
      const summary = normalizeSummary(result?.text);
      if (!summary) {
        // A 200 with nothing usable in it is a failure, not a summary. Try
        // again rather than seed the next session with an empty string.
        lastError = "the model returned an empty summary";
        continue;
      }
      return {
        summary,
        summarized: opts.messages.length,
        transcriptChars: transcript.length,
        usage: {
          promptTokens: result.usage?.inputTokens ?? 0,
          completionTokens: result.usage?.outputTokens ?? 0,
          totalTokens: (result.usage?.inputTokens ?? 0) + (result.usage?.outputTokens ?? 0),
        },
        attempts: attempt,
      };
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
      if (opts.signal?.aborted) break;
    }
  }

  throw new CompactionFailed(
    `Could not summarize this session${lastError ? `: ${lastError}` : ""}. The conversation is unchanged.`,
    MAX_COMPACTION_ATTEMPTS,
  );
}
